#! /usr/bin/env python3

"""
Remove all docker containers that are both running and stopped.
"""

import os


def main():
    try:
        command = f"docker rm -f $(docker ps -a -q)"

        os.system(command)

    except:
        print("Error!")


if __name__ == '__main__':
    main()
