#! /usr/bin/env python3

"""
Activate the virtual environment.
"""

from pathlib import Path
import os
import subprocess
import sys

activate_path = "bin/activate"
home = str(Path.home())
general_venv_path = os.path.join(home, ".venv")
general_activate_path = os.path.join(general_venv_path, activate_path)


def help():
    print("""
        Usage: pyenv [env_name]
        If no arguments, then activate the general virtual environment.
        if [env_name] is given, then activate the specific virtual environment in the current folder
        """)
    sys.exit(1)


def activate(venv_path=general_venv_path):
    activate_script = os.path.join(venv_path, activate_path)

    if not os.path.exists(activate_script):
        print(f"Error: No activation script was found in {activate_script}")
        return

    # Ejecutar un shell interactivo con el entorno activado
    subprocess.run(f"bash --rcfile <(echo 'source {activate_script}')", shell=True, executable="/bin/bash")


def main():
    try:
        # If not arguments, activate the virtual environment
        if len(sys.argv) == 1 or sys.argv[1] == "activate":
            activate()
        elif sys.argv[1] == "help" or sys.argv[1] == "-h" or sys.argv[1] == "--help":
            help()
        else:
            # If arguments are given, activate the specific virtual environment
            env_name = sys.argv[1]
            activate(f"./{env_name}")
    except:
        print(f"Error!")


if __name__ == '__main__':
    main()
